services:

  nginx:
    image: nginx:1.28
    container_name: magento-nginx
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html
      - ./env/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php83
    container_name: magento-php
    volumes:
      - ./src:/var/www/html
      - ./env/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./env/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  mariadb:
    image: mariadb:11.4
    container_name: magento-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: magento
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:3.0.0
    container_name: magento-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
    volumes:
      - ./opensearch:/usr/share/opensearch/data

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: magento-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: magento123
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  valkey:
    image: valkey/valkey:8
    container_name: magento-valkey
    ports:
      - "6379:6379"
    volumes:
      - ./valkey:/data

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.20
    container_name: magento-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin123
    volumes:
      - ./artemis:/var/lib/artemis-instance

  cron:
    build:
      context: .
      dockerfile: Dockerfile-php83
    container_name: magento-cron
    volumes:
      - ./src:/var/www/html
    entrypoint: ["bash", "-c", "while true; do php /var/www/html/bin/magento cron:run; sleep 60; done"]
